### ISSUE TITLE
cfg import error on velvet assasin file 

### ISSUE THREAD

**Issue by xalteropsx** [xormenter/Blender-Anno-.cfg-Import-Addon#17]
```IMPORTING FILE X:\bloodyspell\player_exdata.cfg
IMPORTING FILE X:\bloodyspell\player_exdata.cfg
IMPORTING FILE X:\bloodyspell\player_exdata.cfg
IMPORTING FILE X:\bloodyspell\player_animations.cfg
IMPORTING FILE X:\bloodyspell\player_exdata.cfg
IMPORTING FILE X:\bloodyspell\player_animations.cfg
IMPORTING FILE X:\bloodyspell\player_exdata.cfg
IMPORTING FILE X:\bloodyspell\player_exdata.cfg
Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_annocfg\operators.py", line 259, in execute
    file_obj = self.import_cfg_file(self.path, "MAIN_FILE_" + self.path.name)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_annocfg\operators.py", line 351, in import_cfg_file
    tree = ET.parse(absolute_path)
  File "X:\blender3.2\3.2\python\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "X:\blender3.2\3.2\python\lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by xalteropsx** [comment]
https://drive.google.com/file/d/1mv6LxCFO7F2JmKdf9HdMRjnJWWhC_lPi/view?usp=sharing
